name             'boost-source'
maintainer       'Scott Saad'
maintainer_email 'saadsj@gmail.com'
license          'Apache 2.0'
description      'Builds/Installs C++ boost library'
long_description 'Builds and installs the C++ boost library from a source tarball'
version          '0.1.1'

depends          'apt'
depends          'build-essential'

supports 'ubuntu'
supports 'debian'
supports 'centos'
supports 'amazon'
supports 'scientific'
supports 'fedora'
supports 'redhat'
supports 'oracle'
